### ISSUE TITLE
Conflict with norcalli/nvim-colorizer.lua

### ISSUE THREAD

**Issue by lcrockett** [RRethy/vim-illuminate#76] opened 2021-06-20 15:16 UTC
**Describe the bug**
When using this plugin in conjunction with `norcalli/nvim-colorizer.lua` and having enabling `nvim-colorizer`, RGB codes that are under the cursor will lose their `nvim-colorizer` highlighting.

**To Reproduce**
1. Install plugin `nvim-colorizer`
2. Install plugin `vim-illuminate`
3. Open a file that has multiple duplicate RGB codes written inside of it
4. Enable `nvim-colorizer`
5. Place cursor on a RGB code text (for instance `#ff0000`) that occurs multiple times in the file

**Expected behavior**
It would be great if RGB codes can be excluded somehow. For instance via a plugin option or using regex pattern matching. I did play around with `g:Illuminate_highlightPriority` but was not able to modify this behaviour.

**Screenshots**
![image](https://user-images.githubusercontent.com/58056722/122679284-8773d580-d1ea-11eb-8af1-d3833914e27f.jpeg)
The cursor is on `#00aa00` at the bottom, making illuminate highlighting the same occurrence at the top.

**Additional context**
N/A

**Comment by RRethy** [comment] 2021-06-20 15:41
Duplicate of https://github.com/RRethy/vim-illuminate/issues/46

**Closed by RRethy** 2021-06-20 15:41 UTC

**Comment by lcrockett** [comment] 2021-06-21 00:21
Apologies for the duplicate, I did not realize `vim-hexokinase` existed. It's much more to my liking then `nvim-colorizer` and it solves my problem by using `foregroundfull`. Cheers !

**Comment by RRethy** [comment] 2021-06-21 00:43
No worries, I think nvim-colorizer has a `foreground` mode you might also want to try. Both nvim-colorizer and vim-hexokinase are about equivalent.

**Comment by lcrockett** [comment] 2021-06-21 01:19
Yep, it has a `foreground` option indeed, but in hindsight it doesn't seem to contrast well with backgrounds of similar colour. For now i'm going to use both plugins in tandem. `nvim-colorizer` to keep highlighting the background and `vim-hexokinase` with the virtual text highlighting (neat feature). This way i'll be able to basically toggle individually between 2 different 'colouring modes' on the fly.
