### ISSUE TITLE
Setting Illuminate_highlightUnderCursor seems to have no effect

### ISSUE THREAD

**Issue by zeitchef** [RRethy/vim-illuminate#90] opened 2021-12-26 23:45 UTC
When setting `vim.g.Illuminate_highlightUnderCursor = 0` in my config, the word under the cursor is still always underlined. However, other settings in my config are being respected.

![Screen Shot 2021-12-27 at 00 43 55](https://user-images.githubusercontent.com/6670659/147422609-b9fdf7a5-94ef-449e-84c2-3639bc4dc61f.jpg)

**Comment by RRethy** [comment] 2021-12-27 19:36
Are you using LSP functionality? Also, there is an issue template, please use it, saying `X doesn't work` isn't useful (especially without a **minimal init.vim**).

**Comment by J-Fields** [comment] 2022-01-08 06:26
I was seeing this - it seemed to be caused by loading `nvim-lspconfig` with packer before `vim-illuminate`. I swapped them and it worked 🤷🏻‍♂️

**Comment by RRethy** [comment] 2022-01-10 05:20
Closing this because of a lack of info from original poster.

**Closed by RRethy** 2022-01-10 05:20 UTC
