### ISSUE TITLE
Super slow LSP (solved)

### ISSUE THREAD

**Issue by kiyoon** [RRethy/vim-illuminate#160] opened 2023-02-07 21:31 UTC
I had this extremely weird behaviour. It happened when I activate a conda environment with lots of packages installed.

[Screencast from 07-02-23 20:29:05.webm](https://user-images.githubusercontent.com/12980409/217369895-26d34d0e-e7ce-47fb-beae-7e7423ea5f9a.webm)

It took me hours to figure out the source of the problem. I noticed that if I remove `require('illuminate').on_attach(client)` in LSP attach, the problem went away.

I thought it's good to share if anyone face the same issue. Also, I want to know why this kind of stuff happens in the old version? Maybe you know why, and you can maybe just remove the deprecated function (or make it do nothing).

**Comment by RRethy** [comment] 2023-02-07 21:55
It's not clear why that deprecated API would be slow without steps to reproduce.

>  and you can maybe just remove the deprecated function (or make it do nothing).

This would break backwards compatibility. Breaking a users config randomly isn't a great experience.

Closing the issue since this isn't something that has come up and support for deprecation functionality is limited.

**Closed by RRethy** 2023-02-07 21:55 UTC

**Comment by kiyoon** [comment] 2023-02-07 21:58
If you make it do nothing, I don't think it will break the backwards compatibility. But fair enough, it was just a suggestion.

**Comment by RRethy** [comment] 2023-02-09 23:29
I pushed a change, it may fix it but I'm not sure, if you have time can you try reproducing with the deprecated API. If not no worries, this isn't high priority.

**Comment by kiyoon** [comment] 2023-02-10 00:12
Hi, thanks for taking a look. I got this error:
![image](https://user-images.githubusercontent.com/12980409/217967755-b9e580c0-3e77-45df-b3c9-faf26062dba9.png)

Tbh I don't know how exactly I can reproduce the issue but I think it happens when I have a conda environment with lots of lots of packages installed.

**Comment by RRethy** [comment] 2023-02-10 01:17
Reverted, will leave as is for now.
