### ISSUE TITLE
`require('illuminate').setup()` instead of `require('illuminate').configure()`

### ISSUE THREAD

**Issue by Zeioth** [RRethy/vim-illuminate#194] opened 2024-03-04 15:00 UTC
`setup()` is the convention, so it would be a good idea to use it instead of `configure()`.

**Comment by RRethy** [comment] 2024-03-05 17:55
Duplicate of https://github.com/RRethy/vim-illuminate/issues/112.

`setup()` was an always has been one of the stupidest things that became a convention for Neovim plugins.

**Closed by RRethy** 2024-03-05 17:55 UTC
